name: Lint and test

on:
  push:

jobs:
  lint-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10.8"

      - name: install check testing framework
        run: sudo apt-get install check -y

      - name: lint
        run: make lint

      - name: build is ok
        run: make

      - name: test
        run: make test
